In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression

In [2]:
data=pd.read_csv("C:\\R DATA SETS\\Boston.csv")

In [3]:
x=data.iloc[:,:12].values
y=data.iloc[:,12].values

In [4]:
model=LinearRegression()

In [18]:
ncvals=cross_val_score(model,x,y,cv=10,scoring="neg_mean_squared_error")
ncvals

array([  -9.17006701,  -14.76188969,  -11.78968809,  -34.93168849,
        -26.8851826 ,  -19.52818886,  -10.70555866, -171.48795123,
        -35.0922184 ,  -11.64765827])

In [23]:
ncvals=cross_val_score(model,x,y,cv=10)
ncvals

array([ 0.73711154,  0.45033638, -0.68072223,  0.64394529,  0.61859224,
        0.74049177,  0.33088987, -0.15010182, -0.86194695,  0.38250967])

In [19]:
cvals=-ncvals
cvals

array([  9.17006701,  14.76188969,  11.78968809,  34.93168849,
        26.8851826 ,  19.52818886,  10.70555866, 171.48795123,
        35.0922184 ,  11.64765827])

In [20]:
np.sqrt(cvals)

array([ 3.02821185,  3.84212047,  3.43361152,  5.91030359,  5.18509234,
        4.41907104,  3.271935  , 13.09534082,  5.92386853,  3.41286658])

In [21]:
np.mean(np.sqrt(cvals))

5.152242174479918

In [22]:
np.sqrt(cvals.mean())

5.882177244011862